### ISSUE TITLE
Cannot install, i have php 8

### ISSUE THREAD

**Issue by Tankonyako** [Allyans3/protobuf-steam-auth#2]
https://hastebin.com/share/ufofesotak.typescript my log

**Comment by Tankonyako** [comment]
PHP 8.1.14 (cli) (built: Jan 13 2023 10:43:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies

**Comment by Tankonyako** [comment]
i also try on two machines, also i try install protobuf from pecl, but this is another. maybe i can help move your package to google protobufs?

**Comment by Allyans3** [comment]
Steam supports the second version of protobuf. Google Protobuf v2 doesn't support php8. 

Nothing will help other than migration Steam to the third version of protobuf.

**Comment by Tankonyako** [comment]
i just trying rewrite protobuf ext, when i do this i write to you

**Comment by Allyans3** [comment]
Ok 👍

**Comment by Tankonyako** [comment]
> Ok 👍

I just make extension, it working on php 8.x, https://github.com/Tankonyako/php-protobuf-php8
But i dont test it on php 7, i also test with your package it not throwing errors and working, also your package has too many deprecated warnings on php 8

**Comment by Tankonyako** [comment]
i also tested, your package working with "php-curl-class/php-curl-class": "^9.13", without deprecated warnings and faster

**Comment by Tankonyako** [comment]
also will be great add steam guard code in login method

**Comment by Tankonyako** [comment]
i also reupload steam-totp without deprecations https://github.com/Tankonyako/php-steam-totp

**Comment by Allyans3** [comment]
Can you upload [Tankonyako/php-protobuf-php8](https://github.com/Tankonyako/php-protobuf-php8) on packagist?

**Comment by Tankonyako** [comment]
> Can you upload [Tankonyako/php-protobuf-php8](https://github.com/Tankonyako/php-protobuf-php8) on packagist?

https://packagist.org/packages/tankonyako/php-protobuf

**Comment by Allyans3** [comment]
Thank you for your fixes. Added support for php 8

**Comment by Tankonyako** [comment]
no problem, write if you need something ❤️ in discord ftsu
