### ISSUE TITLE
This is a stub file for IDEs, don't use it directly!

### ISSUE THREAD

**Issue by jadonbrownza** [Allyans3/protobuf-steam-auth#4]
Hi, thank you for your efforts in managing this repo.

The installation instructions are not working for PHP 8.2. The make commands are specifically bombing out with incorrect arguments given to functions.

I've managed to install the protobuf extension using `sudo apt install php8.2-protobuf`, but I still see `This is a stub file for IDEs, don't use it directly!`.

_Originally posted by @scheMeZa in https://github.com/Allyans3/protobuf-steam-auth/issues/1#issuecomment-1574953589_

**Comment by Allyans3** [comment]
Added support for php 8.

To use this package you need to install php extension `protobuf` from the README installation instruction.
