### ISSUE TITLE
Step 3 not enough tutorial

### ISSUE THREAD

**Issue by umpak** [Allyans3/protobuf-steam-auth#6]
@Allyans3  helpppppppppp, I cant install the command

```
phpize
./configure
make
make install
```

its not working for me

Do I make a file protobuf.so?
and put a code inside it

cd protobuf-ext/php8

```
phpize
./configure
make
make install
```

@Allyans3 help me pleaseeee 😩

**Comment by Allyans3** [comment]
> Do I make a file protobuf.so?

You need to generate protobuf.so php extension file using this commands:
```
phpize
./configure
make
make install
```

**Comment by Allyans3** [comment]
If you are using Windows, this video may help you https://www.youtube.com/watch?v=wVnfw5exxGI&ab_channel=Dave

**Comment by umpak** [comment]
I got this error right now
The php-devel package is required for use of this command.

```
[u129136188@sg-nme-web624 php8]$
[u129136188@sg-nme-web624 php8]$ phpize
Can't find PHP headers in /usr/include/php
The php-devel package is required for use of this command.
[u129136188@sg-nme-web624 php8]$ ./configure
-bash: ./configure: No such file or directory
[u129136188@sg-nme-web624 php8]$ make
-bash: make: command not found
[u129136188@sg-nme-web624 php8]$ make install
-bash: make: command not found
[u129136188@sg-nme-web624 php8]$
```

**Comment by umpak** [comment]
this is a mess up for me, php-devel is required to buy a VPS hosting plan in Hostinger to install and use php-devel

**Comment by umpak** [comment]
what is the best hosting for website, please help me @Allyans3

**Comment by umpak** [comment]
is there a way to get Steam cookies using another library that no need extensions? like protobuf.so
my hosting can't give it to me, they said need a VPS 😔😔
my PHP website has been almost 1 week of maintenance already,
I cant get my country Steam market price, because i cant get the steamCurrencyID
and I cant send automatic trade offer, i don't know what to do

**Comment by Allyans3** [comment]
1. Have you tried googling PHP related errors? Can you try first answer https://stackoverflow.com/questions/20827704/phpize-cant-find-php-headers-in-usr-include-php ?
2. What version of php are you using?
3. Try another VPS hosting, not Hostinger.

**Comment by umpak** [comment]
1. this the result in number 1
```
[u129136188@sg-nme-web624 ~]$ phpize
Can't find PHP headers in /usr/include/php
The php-devel package is required for use of this command.
[u129136188@sg-nme-web624 ~]$ yum install php-devel
-bash: yum: command not found
[u129136188@sg-nme-web624 ~]$ yum install php-pear
-bash: yum: command not found
[u129136188@sg-nme-web624 ~]$ pecl install Xdebug
-bash: pecl: command not found
[u129136188@sg-nme-web624 ~]$
```

2. PHP 8.1.18

3. Im not using VPS, hostinger said i need to buy their VPS plan, VPS hosting is required? not web hosting?
or maybe there is another php library to get Steam cookie?

**Comment by Allyans3** [comment]
Yes, you need VPS/VDS. I don't know another php library.

**Comment by umpak** [comment]
Thank you so much, I will let you know
I will order a VPS next week,
I will update you soon, you are great and you help me very much @Allyans3
